spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-sec-jwt-application-db?useSSL=false&serverTimezone=UTC
    username: root
    password: root12345
    #    url: jdbc:mysql://eafinalproject.mysql.database.azure.com:3306/final_project_ea
    #    username: azure_root
    #    password: Root12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9000

